update trocado para delete real
gajigo/backend-spring pull request #14
Opened 2022-08-09 22:58 UTC by Changzer

@SQLDelete fazia um UPDATE, na database, desativando a entrada e colocando um timestamp no lugar.
agora o delete é real com o @RepositoryRestResource.

2022-08-10 22:58 UTC, Changzer commented
trocamos pra este approach, pois o @SQLDelete fazia um update, desativando a entrada e deixando um timestamp de quando foi feito a modificação.
agora a entrada pode ser dropada de vez na database, deletando definitivamente a linha de entrada, diferenciando o DELETAR do DESATIVAR no nosso sistema.

2022-08-10 23:01 UTC, pehdfms commented
Mas por que foi mudada aquela linha especificamente? acho que as mudanças que eram do SQLDelete eram todas aquelas anotações que você deletou, não?

2022-08-10 23:09 UTC, Changzer commented
justamente, por isso removi o SQLDelete... pois ele fazia um update ao invés de drop :)

2022-08-10 23:10 UTC, pehdfms commented
sim, isso está certo. estou perguntado sobre essa linha que eu comentei.
![image](https://user-images.githubusercontent.com/35301623/184038329-9059b0d9-1f30-46d6-96c1-68368c04f50c.png)

isso não tem a ver com a mudança do SQLDelete, mas foi feito por algum motivo especifico?

2022-08-11 23:29 UTC, pehdfms commented on src/main/java/br/com/uniamerica/gajigo/entity/AbstractEntity.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE)
Por que foi mudada essa estrategia?

2022-08-11 23:29 UTC, Changzer commented
esse @GeneratedValue nao fui eu quem deletei.
nao tenho nada a ver com isso. só modifiquei @SQLDelete :)

2022-08-11 23:30 UTC, pehdfms requested changes

2022-08-11 23:30 UTC, pehdfms commented on src/main/java/br/com/uniamerica/gajigo/entity/AbstractEntity.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE)
```suggestion
    @GeneratedValue(strategy = GenerationType.IDENTITY)
```

2022-08-11 23:33 UTC, pehdfms approved these changes

2022-08-11 23:33 UTC, merged