Event repository test
gajigo/backend-spring pull request #17
Opened 2022-08-16 00:18 UTC by edua2127

2022-08-22 00:16 UTC, pehdfms requested changes

2022-08-22 00:16 UTC, pehdfms commented on pom.xml
> +        </dependency>
não parece que o codigo esteja usando essas dependencias, tem algo que não estou vendo?

2022-08-22 00:16 UTC, pehdfms commented on src/test/java/br/com/uniamerica/gajigo/unit/repository/UserRepositoryTest.java
> +
espaço extra no final da linha, espaço invisivel embaixo dela.

2022-08-22 00:16 UTC, pehdfms commented on src/main/java/br/com/uniamerica/gajigo/entity/User.java
> +
sem espaços no final da classe

2022-08-22 00:16 UTC, pehdfms commented on src/main/java/br/com/uniamerica/gajigo/entity/User.java
> +
só um espaço entre fields / metodos.

2022-08-22 00:16 UTC, pehdfms commented on src/main/java/br/com/uniamerica/gajigo/entity/AbstractEntity.java
> +    protected LocalDateTime created;
Não parece estar sendo usado em outro lugar, deixa como private.

2022-08-22 00:16 UTC, pehdfms commented on src/test/java/br/com/uniamerica/gajigo/integration/AbstractIntegrationTest.java
> +        return this.mockMvc.perform(MockMvcRequestBuilders.get(path + "/" + id).accept("application/json"))
jogue o .get e .accept para novas linhas, essa ficou muito longa.

2022-08-22 00:16 UTC, pehdfms commented on src/test/java/br/com/uniamerica/gajigo/integration/AbstractIntegrationTest.java
> +    ResultActions getById(String path, Long id) throws Exception {
espaço entre metodos, serve para todos arquivos.

2022-08-22 00:16 UTC, pehdfms commented on src/test/java/br/com/uniamerica/gajigo/integration/EventTest.java
> +    public String createUser() {
Coloque isso no UserTest. Criar um usuario não é responsabilidade do Evento.

2022-08-22 00:16 UTC, pehdfms commented on src/test/java/br/com/uniamerica/gajigo/integration/EventTest.java
> +                "}";
![image](https://user-images.githubusercontent.com/35301623/185817253-6324056a-09a1-4940-849d-262f299db324.png)
Por conveniencia e facilidade de leitura use o ObjectMapper. mesmo que o objeto em si não consiga ser serializado direto da para criar as variaveis de uma maneira mais dinamica. (sem ter que abusar dos \ para cortar aspas)

2022-08-22 00:16 UTC, pehdfms commented on src/test/java/br/com/uniamerica/gajigo/integration/EventTest.java
> +        post(caminho, createUser()).andExpect(status().is2xxSuccessful());
não sou fã do teste de evento dando post em um usuario, não poderiamos usar o UserTest para isso?

2022-08-22 00:16 UTC, pehdfms commented on src/test/java/br/com/uniamerica/gajigo/integration/UserTest.java
> +
remove esses dois espaços entre esse import.

2022-08-22 00:16 UTC, pehdfms commented on src/test/java/br/com/uniamerica/gajigo/integration/UserTest.java
> +    @Test
Espaço entre metodos.

2022-08-22 00:16 UTC, pehdfms commented on src/test/java/br/com/uniamerica/gajigo/unit/repository/EventRepositoryTest.java
> +
Remova um desses espaços.

2022-08-22 00:16 UTC, pehdfms commented on src/test/java/br/com/uniamerica/gajigo/unit/repository/EventRepositoryTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Adicione um espaço antes desse import static.

2022-08-22 00:19 UTC, pehdfms commented on src/test/java/br/com/uniamerica/gajigo/integration/EventTest.java
> +                "}";
https://attacomsian.com/blog/jackson-create-json-object

2022-08-22 00:20 UTC, pehdfms commented on src/test/java/br/com/uniamerica/gajigo/integration/EventTest.java
> +                "}";
outro beneficio é que você pode criar uma função que só te retorne o JSON antes de dar .build() e dai se você precisa adicionar / remover / modificar algum field dentro de um teste especifico é só chamar essa função, fazer a modficação e chamar .build()

2022-08-22 00:45 UTC, edua2127 commented on src/test/java/br/com/uniamerica/gajigo/unit/repository/UserRepositoryTest.java
> +
@pehdfms

2022-08-22 00:45 UTC, edua2127 commented on src/main/java/br/com/uniamerica/gajigo/entity/User.java
> +
@pehdfms

2022-08-22 00:46 UTC, edua2127 commented on src/main/java/br/com/uniamerica/gajigo/entity/User.java
> +
@pehdfms

2022-08-22 00:47 UTC, edua2127 commented on src/main/java/br/com/uniamerica/gajigo/entity/AbstractEntity.java
> +    protected LocalDateTime created;
@pehdfms

2022-08-22 00:57 UTC, edua2127 commented on src/test/java/br/com/uniamerica/gajigo/integration/UserTest.java
> +
@pehdfms

2022-08-22 00:59 UTC, edua2127 commented on src/test/java/br/com/uniamerica/gajigo/unit/repository/EventRepositoryTest.java
> +
@pehdfms

2022-08-22 00:59 UTC, edua2127 commented on src/test/java/br/com/uniamerica/gajigo/unit/repository/EventRepositoryTest.java
> +import static org.junit.jupiter.api.Assertions.*;
@pehdfms

2022-08-22 00:59 UTC, edua2127 commented on src/test/java/br/com/uniamerica/gajigo/integration/UserTest.java
> +    @Test
@pehdfms

2022-08-22 22:21 UTC, edua2127 commented on src/test/java/br/com/uniamerica/gajigo/integration/EventTest.java
> +        post(caminho, createUser()).andExpect(status().is2xxSuccessful());
@pehdfms

2022-08-22 22:26 UTC, edua2127 commented on src/test/java/br/com/uniamerica/gajigo/integration/AbstractIntegrationTest.java
> +        return this.mockMvc.perform(MockMvcRequestBuilders.get(path + "/" + id).accept("application/json"))
@pehdfms

2022-08-22 22:26 UTC, pehdfms requested changes

2022-08-22 22:26 UTC, pehdfms commented on src/main/java/br/com/uniamerica/gajigo/entity/User.java
> -    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
Não pode ser feito isso! se ficar sem essa anotação a senha vai ser exposta ao consumidor da API. a unica maneira que deveriamos "expor" essa informação é indiretamente pela rota de login.

2022-08-22 22:26 UTC, pehdfms commented on src/test/java/br/com/uniamerica/gajigo/integration/AbstractIntegrationTest.java
> +    ResultActions getById(String path, Long id) throws Exception {
ainda precisa ser adicionado um espaço aqui. Não crie os metodos com as chaves batendo com a definição.

2022-08-22 22:26 UTC, pehdfms commented on src/test/java/br/com/uniamerica/gajigo/integration/EventTest.java
> +
uma linha a mais do que necessario aqui.

2022-08-22 22:27 UTC, edua2127 commented on src/test/java/br/com/uniamerica/gajigo/integration/AbstractIntegrationTest.java
> +    ResultActions getById(String path, Long id) throws Exception {
@pehdfms

2022-08-22 23:35 UTC, edua2127 commented on src/test/java/br/com/uniamerica/gajigo/integration/EventTest.java
> +    public String createUser() {
@pehdfms

2022-08-22 23:35 UTC, edua2127 commented on src/test/java/br/com/uniamerica/gajigo/integration/EventTest.java
> +                "}";
@pehdfms

2022-08-22 23:36 UTC, edua2127 commented on src/main/java/br/com/uniamerica/gajigo/entity/User.java
> -    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
@pehdfms

2022-08-22 23:36 UTC, edua2127 commented on src/test/java/br/com/uniamerica/gajigo/integration/EventTest.java
> +
@pehdfms

2022-08-22 23:41 UTC, pehdfms requested changes

2022-08-22 23:41 UTC, pehdfms commented on src/test/java/br/com/uniamerica/gajigo/integration/EventTest.java
> +                "}";
Esse json deveria usar o ObjectMapper

2022-08-22 23:42 UTC, edua2127 commented on src/test/java/br/com/uniamerica/gajigo/integration/EventTest.java
> +                "}";
@pehdfms

2022-08-22 23:45 UTC, pehdfms commented on src/test/java/br/com/uniamerica/gajigo/integration/EventTest.java
> +        post(path, createEvent()).andExpect(status().is2xxSuccessful());
use o status certo para cada request.

2022-08-23 00:27 UTC, edua2127 commented on src/test/java/br/com/uniamerica/gajigo/integration/EventTest.java
> +        post(path, createEvent()).andExpect(status().is2xxSuccessful());
@pehdfms

2022-08-23 00:28 UTC, pehdfms commented on src/test/java/br/com/uniamerica/gajigo/integration/AbstractIntegrationTest.java
> +    }
faça esse metodo setar removed: true direto, sem ter que fazer o consumidor usar isso.

2022-08-23 00:28 UTC, pehdfms commented on src/test/java/br/com/uniamerica/gajigo/integration/UserTest.java
sem linha branca no inicio de funções.

2022-08-23 00:31 UTC, edua2127 commented on src/test/java/br/com/uniamerica/gajigo/integration/AbstractIntegrationTest.java
> +    }
@pehdfms

2022-08-23 00:32 UTC, edua2127 commented on src/test/java/br/com/uniamerica/gajigo/integration/UserTest.java
@pehdfms

2022-08-23 00:32 UTC, pehdfms approved these changes

2022-08-24 00:01 UTC, merged