Integration Test for Lectures
gajigo/backend-spring pull request #37
Opened 2022-09-13 22:36 UTC by JeanClay

2022-09-13 23:14 UTC, pehdfms requested changes

2022-09-13 23:14 UTC, pehdfms commented on src/test/java/br/com/uniamerica/gajigo/integration/LectureTest.java
> +        return mapper.writerWithDefaultPrettyPrinter().writeValueAsString(event);
Linha branca entre conteudo e return

2022-09-13 23:14 UTC, pehdfms commented on src/test/java/br/com/uniamerica/gajigo/integration/LectureTest.java
> +        interval.put("startDate", "2023-07-15T00:00:00");
linha nova aqui

2022-09-13 23:14 UTC, pehdfms commented on src/test/java/br/com/uniamerica/gajigo/integration/LectureTest.java
> +        user.put("name", "name");
linha nova aqui

2022-09-13 23:14 UTC, pehdfms commented on src/test/java/br/com/uniamerica/gajigo/integration/LectureTest.java
> +    public String createUser() throws JsonProcessingException {
esse tipo de função geradora deveria fazer parte de whateverTest, não faz sentido a gente recriar esses fakes toda vez que a gente tiver uma relação.
isso aplica para todos createAlgo que não sejam createLecture.
pontos bonus se você criar uma interface comum aqui usando o AbstractIntegrationTest: talvez sete um create obrigatorio?
```java
abstract String create() throws JsonProcessingException;
```

2022-09-13 23:14 UTC, pehdfms commented on src/test/java/br/com/uniamerica/gajigo/integration/LectureTest.java
> +
relacionado com a review do create, se possivel faça o create dar post direto para que a gente não precise depender de setar path toda hora. Também deveriamos criar overloads do AbstractIntegrationTest para só chamar o path que a gente já tem salvo
```java
??? get(Long id) {
    ... // usando this.path para o path.
}
```

2022-09-15 00:09 UTC, carmoIn commented on src/test/java/br/com/uniamerica/gajigo/integration/LectureTest.java
> +
Espaço extra

2022-09-15 00:10 UTC, carmoIn approved these changes

2022-09-15 00:22 UTC, pehdfms approved these changes
LGTM

2022-09-15 00:22 UTC, merged